services:
  # PostgreSQL 資料庫
  db:
    image: postgres:14
    container_name: rentrent-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rentrent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis 緩存
  redis:
    image: redis:7-alpine
    container_name: rentrent-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Python 爬蟲服務 (可選，可以直接在宿主機運行)
  crawler:
    build:
      context: ./apps/crawler
      dockerfile: Dockerfile
    container_name: rentrent-crawler
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rentrent?schema=public
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./apps/crawler:/app
    profiles:
      - crawler  # 使用 profile 讓爬蟲變成可選服務

volumes:
  postgres_data:
  redis_data: 