version: '3.8'

services:
  app:
    build: .
    container_name: python-app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: python app.py 